#!/bin/bash

#  This file gives some sample cmake invocations.  You may wish to
#  edit some options that are chosen here.

#  For information on how to get cmake, visit this page:
#  https://ambermd.org/pmwiki/pmwiki.php/Main/CMake-Quick-Start

#  For information on common options for cmake, visit this page:
#  http://ambermd.org/pmwiki/pmwiki.php/Main/CMake-Common-Options

#  (Note that you can change the value of CMAKE_INSTALL_PREFIX from what
#  is suggested below, but it cannot coincide with the amber24_src
#  folder.)

AMBER_PREFIX=$(dirname $(dirname `pwd`))

cmake $AMBER_PREFIX/amber24_src \
  -DCMAKE_INSTALL_PREFIX=$AMBER_PREFIX/amber24 \
  -DCOMPILER=GNU  \
  -DMPI=FALSE -DCUDA=TRUE -DINSTALL_TESTS=TRUE \
  -DDOWNLOAD_MINICONDA=FALSE \
  -DUSE_CONDA_LIBS=TRUE \
  -DCHECK_UPDATES=FALSE \
  2>&1 | tee  cmake.log

# Use the miniconda already in the base image + already installed the required conda packages
# Need to use the conda libs to ensure consistent search path for some libraries
# No need to check for updates as already done earlier in the build process
# Cannot build -DSTATIC due to the CUDA libraries

if [ ! -s cmake.log ]; then
  echo ""
  echo "Error:  No cmake.log file created: you may need to edit run_cmake"
  exit 1
fi

echo ""
echo "If errors are reported, search for 'CMake Error' in the cmake.log file."
echo ""
echo "If the cmake build report looks OK, you should now do the following:"
echo ""
echo "    make install"
echo "    source $AMBER_PREFIX/amber24/amber.sh"
echo ""
echo "Consider adding the last line to your login startup script, e.g. ~/.bashrc"
echo ""
